[phases.setup]
nixPkgs = ['python310', 'postgresql', 'gcc']

[phases.install]
cmd = "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install poetry==1.2.2 && poetry install --no-dev --no-interaction --no-ansi"
