# Generated by Django 4.1.3 on 2022-12-02 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('name', models.CharField(
                    max_length=100,
                    unique=True,
                    verbose_name='name')),
                ('created_at', models.DateTimeField(
                    default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
