# Generated by Django 4.1.3 on 2022-11-21 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=100,
                                          unique=True)),
                ('created_at',
                 models.DateTimeField(
                     default=datetime.datetime(2022, 11, 21, 6, 30, 35,
                                               276038, tzinfo=datetime
                                               .timezone.utc))),
            ],
        ),
    ]
