# Generated by Django 4.1.3 on 2022-11-25 06:11

from django.db import migrations, models
import task_manager.status.utils


class Migration(migrations.Migration):
    dependencies = [
        ('status', '0002_alter_status_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True,
                validators=[task_manager.status.utils.validate_status_naming]),
        ),
    ]
