# Generated by Django 4.1.3 on 2022-11-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0004_alter_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True,
                verbose_name='name'),
        ),
    ]
