# Generated by Django 4.1.3 on 2022-11-25 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0003_alter_status_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='task_creator',
                    to=settings.AUTH_USER_MODEL)),
                ('executor', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='task_executor',
                    to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='task_status',
                    to='status.status')),
            ],
        ),
    ]
