# Generated by Django 4.1.3 on 2022-11-25 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_alter_status_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='task_creator',
                to=settings.AUTH_USER_MODEL,
                verbose_name='task creator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True,
                                   verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='task_executor',
                to=settings.AUTH_USER_MODEL,
                verbose_name='task executor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255,
                                   unique=True,
                                   verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='task_status',
                to='status.status',
                verbose_name='task status'),
        ),
    ]
