# Generated by Django 4.1.3 on 2022-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0004_alter_task_options_alter_task_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(
                blank=True,
                related_name='labels',
                through='tasks.TaskLabelRelation',
                to='labels.label',
                verbose_name='labels'),
        ),
    ]
